languageCode = "en-us"
title = "Patrick Nollet"
baseurl = "https://patrick.nollet.org/"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-94068910-1"
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About me"
    url = "/about-me/"

[params]
    description = ""
    twitter = "PatrickNLT"
    github = "PatrickNLT"
    linkedin = "patricknollet"

    [params.logo]
    url = "images/patricknollet-nav.jpg"
    width = 50
    height = 50
    alt = "Patrick Nollet"